name: IridiumSkyblock
version: 3.2.10-hotfix-1.2
description: Habitats [Built off IridiumSkyblock]
main: com.iridium.iridiumskyblock.IridiumSkyblock
api-version: '1.13'
author: Peaches_MLG
depend: [ Vault ]
softdepend:
  - "MVdWPlaceholderAPI"
  - "PlaceholderAPI"
  - "Essentials"
  - "EssentialsSpawn"
  - "RoseStacker"
  - "WorldEdit"
  - "Multiverse-Core"
loadbefore:
#  - "Multiverse-Core"
commands:
  iridiumskyblock:
    aliases: [ "habitat", h ]
    description: Main plugin command
